image:
  repository: ghcr.io/forumviriumhelsinki/cesium-dashboard
  tag: v0.5.1
imagePullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-login-secret
gateway:
  enabled: true
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
  - host: cesium-dashboard.dataportal.fi
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - cesium-dashboard.dataportal.fi
    secretName: cesium-dashboard-tls # pragma: allowlist secret
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
keda:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Helsinki
      start: 0 7 * * 1-5
      end: 0 18 * * 1-5
      desiredReplicas: "1"
